### ISSUE TITLE
Temperature set always stay at 20

### ISSUE THREAD

**Issue by EricBerdah** [ouinouin/Berryton#2]
Hi,
the last release is now running without error,
but it's impossible to set the temp, it always return at the same value, in my case 20

below the log with  acmode off and heat

thank's

19:31:09.671 function MQTTSubscribeDispatcher : sending frame to AC unit:  bytes('7A7A21D5180000A10000000000010198000000000000286B')
19:31:09.813 function GetFrametype : valid message from AC unit : bytes('7A7AD521220000A30A0A1600000001019800000000046401DC444231313337303D85')
19:31:09.826 function GetACmode :  ACmodeString =  off
19:31:09.828 function GetFanSpeed : FanModeString =  auto
19:31:09.831 function GetOscillationMode : OscillationModeString =  on
19:31:09.844 function GetInternalTemperature : internal unit temperature:  22
19:31:09.846 function GetTemperatureSetpoint : TemperatureSetpoint :  20
19:31:09.848 function PublishFeedback : got all needed value, publishing in mqtt topics
19:31:09.862 MQT: CHAUFFAGE/SALON_ANNEXE/tele/mode/get = off
19:31:09.865 MQT: CHAUFFAGE/SALON_ANNEXE/tele/fan/get = auto
19:31:09.868 MQT: CHAUFFAGE/SALON_ANNEXE/tele/swing/get = on
19:31:09.884 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualtemp/get = 22
19:31:09.886 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualsetpoint/get = 20
19:31:48.617 CMD: publish CHAUFFAGE/SALON_ANNEXE/cmnd/temperature/set 25
19:31:48.622 MQT: CHAUFFAGE/SALON_ANNEXE/cmnd/temperature/set = 25
19:31:49.138 function MQTTSubscribeDispatcher : actual FanSpeedSetpoint =  auto
19:31:49.149 function MQTTSubscribeDispatcher : actual OscillationModeSetpoint =  on
19:31:49.161 function MQTTSubscribeDispatcher : actual TemperatureSetpoint =  20
19:31:49.164 function MQTTSubscribeDispatcher : received TemperatureSetpoint =  20
19:31:49.176 function MQTTSubscribeDispatcher : publishing immediately TemperatureSetpoint
19:31:49.180 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualsetpoint/get = 25
19:31:49.184 function forgepayload : Register 13 ,temperature setpoint -16 :  1
19:31:49.219 function MQTTSubscribeDispatcher : sending frame to AC unit:  bytes('7A7A21D5180000A10000000000010198000000000000286B')
19:31:49.269 function GetFrametype : valid message from AC unit : bytes('7A7AD521220000A30A0A1600000001019800000000046401DC444231313337303D85')
19:31:49.282 function GetACmode :  ACmodeString =  off
19:31:49.285 function GetFanSpeed : FanModeString =  auto
19:31:49.287 function GetOscillationMode : OscillationModeString =  on
19:31:49.290 function GetInternalTemperature : internal unit temperature:  22
19:31:49.303 function GetTemperatureSetpoint : TemperatureSetpoint :  20
19:31:49.304 function PublishFeedback : got all needed value, publishing in mqtt topics
19:31:49.319 MQT: CHAUFFAGE/SALON_ANNEXE/tele/mode/get = off
19:31:49.322 MQT: CHAUFFAGE/SALON_ANNEXE/tele/fan/get = auto
19:31:49.325 MQT: CHAUFFAGE/SALON_ANNEXE/tele/swing/get = on
19:31:49.329 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualtemp/get = 22
19:31:49.342 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualsetpoint/get = 20
19:31:49.363 function MQTTSubscribeDispatcher : message received from mqtt
19:31:49.365 function MQTTSubscribeDispatcher : actual ACmode =  off
19:31:49.368 function MQTTSubscribeDispatcher : actual FanSpeedSetpoint =  auto
19:31:49.380 function MQTTSubscribeDispatcher : actual OscillationModeSetpoint =  on
19:31:49.382 function MQTTSubscribeDispatcher : actual TemperatureSetpoint =  20
19:31:49.394 function MQTTSubscribeDispatcher : received TemperatureSetpoint =  20
19:31:49.396 function MQTTSubscribeDispatcher : publishing immediately TemperatureSetpoint
19:31:49.410 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualsetpoint/get = 25 °C
19:31:49.414 function forgepayload : Register 13 ,temperature setpoint -16 :  1
19:31:49.452 function MQTTSubscribeDispatcher : sending frame to AC unit:  bytes('7A7A21D5180000A10000000000010198000000000000286B')
19:31:49.591 function GetFrametype : valid message from AC unit : bytes('7A7AD521220000A30A0A1600000001019800000000046401DC444231313337303D85')
19:31:49.605 function GetACmode :  ACmodeString =  off
19:31:49.607 function GetFanSpeed : FanModeString =  auto
19:31:49.610 function GetOscillationMode : OscillationModeString =  on
19:31:49.612 function GetInternalTemperature : internal unit temperature:  22
19:31:49.625 function GetTemperatureSetpoint : TemperatureSetpoint :  20
19:31:49.627 function PublishFeedback : got all needed value, publishing in mqtt topics
19:31:49.641 MQT: CHAUFFAGE/SALON_ANNEXE/tele/mode/get = off
19:31:49.644 MQT: CHAUFFAGE/SALON_ANNEXE/tele/fan/get = auto
19:31:49.647 MQT: CHAUFFAGE/SALON_ANNEXE/tele/swing/get = on
19:31:49.650 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualtemp/get = 22
19:31:49.663 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualsetpoint/get = 20
19:31:49.927 function MQTTSubscribeDispatcher : message received from mqtt
19:31:49.929 function MQTTSubscribeDispatcher : actual ACmode =  off
19:31:49.931 function MQTTSubscribeDispatcher : actual FanSpeedSetpoint =  auto
19:31:49.942 function MQTTSubscribeDispatcher : actual OscillationModeSetpoint =  on
19:31:49.954 function MQTTSubscribeDispatcher : actual TemperatureSetpoint =  20
19:31:49.956 function MQTTSubscribeDispatcher : received TemperatureSetpoint =  20
19:31:49.968 function MQTTSubscribeDispatcher : publishing immediately TemperatureSetpoint
19:31:49.972 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualsetpoint/get = 20
19:31:49.976 function forgepayload : Register 13 ,temperature setpoint -16 :  1
19:31:50.015 function MQTTSubscribeDispatcher : sending frame to AC unit:  bytes('7A7A21D5180000A10000000000010198000000000000286B')
19:31:50.044 function MQTTSubscribeDispatcher : message received from mqtt
19:31:50.046 function MQTTSubscribeDispatcher : actual ACmode =  off
19:31:50.048 function MQTTSubscribeDispatcher : actual FanSpeedSetpoint =  auto
19:31:50.060 function MQTTSubscribeDispatcher : actual OscillationModeSetpoint =  on
19:31:50.072 function MQTTSubscribeDispatcher : actual TemperatureSetpoint =  20
19:31:50.074 function MQTTSubscribeDispatcher : received TemperatureSetpoint =  20
19:31:50.086 function MQTTSubscribeDispatcher : publishing immediately TemperatureSetpoint
19:31:50.090 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualsetpoint/get = 20 °C
19:31:50.097 function forgepayload : Register 13 ,temperature setpoint -16 :  1
19:31:50.122 function MQTTSubscribeDispatcher : sending frame to AC unit:  bytes('7A7A21D5180000A10000000000010198000000000000286B')
19:31:50.398 function GetFrametype : valid message from AC unit : bytes('7A7AD521220000A30A0A1600000001019800000000046401DC444231313337303D85')
19:31:50.411 function GetACmode :  ACmodeString =  off
19:31:50.414 function GetFanSpeed : FanModeString =  auto
19:31:50.417 function GetOscillationMode : OscillationModeString =  on
19:31:50.419 function GetInternalTemperature : internal unit temperature:  22
19:31:50.431 function GetTemperatureSetpoint : TemperatureSetpoint :  20
19:31:50.433 function PublishFeedback : got all needed value, publishing in mqtt topics
19:31:50.447 MQT: CHAUFFAGE/SALON_ANNEXE/tele/mode/get = off
19:31:50.451 MQT: CHAUFFAGE/SALON_ANNEXE/tele/fan/get = auto
19:31:50.454 MQT: CHAUFFAGE/SALON_ANNEXE/tele/swing/get = on
19:31:50.457 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualtemp/get = 22
19:31:50.470 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualsetpoint/get = 20
19:32:08.651 CMD: publish CHAUFFAGE/SALON_ANNEXE/cmnd/mode/heat
19:32:08.656 MQT: CHAUFFAGE/SALON_ANNEXE/cmnd/mode/heat = 
19:32:08.712 MQT: CHAUFFAGE/SALON_ANNEXE/stat/RESULT = {"Command":"Unknown"}
19:32:21.892 CMD: publish CHAUFFAGE/SALON_ANNEXE/cmnd/mode/set heat
19:32:21.897 MQT: CHAUFFAGE/SALON_ANNEXE/cmnd/mode/set = heat
19:32:22.145 function MQTTSubscribeDispatcher : message received from mqtt
19:32:22.147 function MQTTSubscribeDispatcher : actual ACmode =  off
19:32:22.149 function MQTTSubscribeDispatcher : actual FanSpeedSetpoint =  auto
19:32:22.161 function MQTTSubscribeDispatcher : actual OscillationModeSetpoint =  on
19:32:22.173 function MQTTSubscribeDispatcher : actual TemperatureSetpoint =  20
19:32:22.174 function MQTTSubscribeDispatcher : received ACmode =  heat
19:32:22.188 MQT: CHAUFFAGE/SALON_ANNEXE/tele/mode/get = heat
19:32:22.190 function MQTTSubscribeDispatcher : publishing immediately ACmode
19:32:22.195 function forgepayload : Register 13 ,temperature setpoint -16 :  1
19:32:22.225 function MQTTSubscribeDispatcher : sending frame to AC unit:  bytes('7A7A21D5180000A1000000000C01019800000000000017AB')
19:32:22.436 function MQTTSubscribeDispatcher : message received from mqtt
19:32:22.437 function MQTTSubscribeDispatcher : actual ACmode =  heat
19:32:22.439 function MQTTSubscribeDispatcher : actual FanSpeedSetpoint =  auto
19:32:22.451 function MQTTSubscribeDispatcher : actual OscillationModeSetpoint =  on
19:32:22.463 function MQTTSubscribeDispatcher : actual TemperatureSetpoint =  20
19:32:22.465 function MQTTSubscribeDispatcher : received ACmode =  heat
19:32:22.479 MQT: CHAUFFAGE/SALON_ANNEXE/tele/mode/get = heat
19:32:22.481 function MQTTSubscribeDispatcher : publishing immediately ACmode
19:32:22.486 function forgepayload : Register 13 ,temperature setpoint -16 :  1
19:32:22.520 function MQTTSubscribeDispatcher : sending frame to AC unit:  bytes('7A7A21D5180000A1000000000C01019800000000000017AB')
19:32:22.574 function GetFrametype : valid message from AC unit : bytes('7A7AD521220000A30A0A1600000C01019800000000046401DC444231313337306C96')
19:32:22.588 function GetACmode :  ACmodeString =  heat
19:32:22.590 function GetFanSpeed : FanModeString =  auto
19:32:22.592 function GetOscillationMode : OscillationModeString =  on
19:32:22.605 function GetInternalTemperature : internal unit temperature:  22
19:32:22.608 function GetTemperatureSetpoint : TemperatureSetpoint :  20
19:32:22.609 function PublishFeedback : got all needed value, publishing in mqtt topics
19:32:22.623 MQT: CHAUFFAGE/SALON_ANNEXE/tele/mode/get = heat
19:32:22.626 MQT: CHAUFFAGE/SALON_ANNEXE/tele/fan/get = auto
19:32:22.629 MQT: CHAUFFAGE/SALON_ANNEXE/tele/swing/get = on
19:32:22.644 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualtemp/get = 22
19:32:22.647 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualsetpoint/get = 20
19:32:22.665 function MQTTSubscribeDispatcher : message received from mqtt
19:32:22.667 function MQTTSubscribeDispatcher : actual ACmode =  heat
19:32:22.671 function MQTTSubscribeDispatcher : actual FanSpeedSetpoint =  auto
19:32:22.683 function MQTTSubscribeDispatcher : actual OscillationModeSetpoint =  on
19:32:22.686 function MQTTSubscribeDispatcher : actual TemperatureSetpoint =  20
19:32:22.698 function MQTTSubscribeDispatcher : received ACmode =  heat
19:32:22.702 MQT: CHAUFFAGE/SALON_ANNEXE/tele/mode/get = heat
19:32:22.705 function MQTTSubscribeDispatcher : publishing immediately ACmode
19:32:22.720 function forgepayload : Register 13 ,temperature setpoint -16 :  1
19:32:22.745 function MQTTSubscribeDispatcher : sending frame to AC unit:  bytes('7A7A21D5180000A1000000000C01019800000000000017AB')
19:32:22.884 function GetFrametype : valid message from AC unit : bytes('7A7AD521220000A30A0A1600000C01019800000000046401DC444231313337306C96')
19:32:22.897 function GetACmode :  ACmodeString =  heat
19:32:22.900 function GetFanSpeed : FanModeString =  auto
19:32:22.902 function GetOscillationMode : OscillationModeString =  on
19:32:22.915 function GetInternalTemperature : internal unit temperature:  22
19:32:22.917 function GetTemperatureSetpoint : TemperatureSetpoint :  20
19:32:22.919 function PublishFeedback : got all needed value, publishing in mqtt topics
19:32:22.934 MQT: CHAUFFAGE/SALON_ANNEXE/tele/mode/get = heat
19:32:22.937 MQT: CHAUFFAGE/SALON_ANNEXE/tele/fan/get = auto
19:32:22.940 MQT: CHAUFFAGE/SALON_ANNEXE/tele/swing/get = on
19:32:22.953 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualtemp/get = 22
19:32:22.956 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualsetpoint/get = 20
19:32:39.861 CMD: publish CHAUFFAGE/SALON_ANNEXE/cmnd/temperature/set 25
19:32:39.866 MQT: CHAUFFAGE/SALON_ANNEXE/cmnd/temperature/set = 25
19:32:40.586 MQT: CHAUFFAGE/SALON_ANNEXE/tele/mode/get = heat
19:32:40.589 MQT: CHAUFFAGE/SALON_ANNEXE/tele/fan/get = auto
19:32:40.592 MQT: CHAUFFAGE/SALON_ANNEXE/tele/swing/get = on
19:32:40.595 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualtemp/get = 22
19:32:40.608 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualsetpoint/get = 20
19:32:40.632 function MQTTSubscribeDispatcher : message received from mqtt
19:32:40.634 function MQTTSubscribeDispatcher : actual ACmode =  heat
19:32:40.636 function MQTTSubscribeDispatcher : actual FanSpeedSetpoint =  auto
19:32:40.648 function MQTTSubscribeDispatcher : actual OscillationModeSetpoint =  on
19:32:40.650 function MQTTSubscribeDispatcher : actual TemperatureSetpoint =  20
19:32:40.662 function MQTTSubscribeDispatcher : received TemperatureSetpoint =  20
19:32:40.674 function MQTTSubscribeDispatcher : internal_thermostat enabled : saving the setpoint to persistance file
19:32:40.676 function MQTTSubscribeDispatcher : publishing immediately TemperatureSetpoint
19:32:40.691 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualsetpoint/get = 25
19:32:40.695 function forgepayload : Register 13 ,temperature setpoint -16 :  1
19:32:40.724 function MQTTSubscribeDispatcher : sending frame to AC unit:  bytes('7A7A21D5180000A1000000000C01019800000000000017AB')
19:32:40.867 function GetFrametype : valid message from AC unit : bytes('7A7AD521220000A30A0A1600000C01019800000000046401DC444231313337306C96')
19:32:40.880 function GetACmode :  ACmodeString =  heat
19:32:40.882 function GetFanSpeed : FanModeString =  auto
19:32:40.885 function GetOscillationMode : OscillationModeString =  on
19:32:40.888 function GetInternalTemperature : internal unit temperature:  22
19:32:40.900 function GetTemperatureSetpoint : TemperatureSetpoint :  20
19:32:40.902 function PublishFeedback : got all needed value, publishing in mqtt topics
19:32:40.916 MQT: CHAUFFAGE/SALON_ANNEXE/tele/mode/get = heat
19:32:40.920 MQT: CHAUFFAGE/SALON_ANNEXE/tele/fan/get = auto
19:32:40.922 MQT: CHAUFFAGE/SALON_ANNEXE/tele/swing/get = on
19:32:40.926 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualtemp/get = 22
19:32:40.940 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualsetpoint/get = 20
19:32:41.205 function MQTTSubscribeDispatcher : message received from mqtt
19:32:41.207 function MQTTSubscribeDispatcher : actual ACmode =  heat
19:32:41.209 function MQTTSubscribeDispatcher : actual FanSpeedSetpoint =  auto
19:32:41.220 function MQTTSubscribeDispatcher : actual OscillationModeSetpoint =  on
19:32:41.232 function MQTTSubscribeDispatcher : actual TemperatureSetpoint =  20
19:32:41.234 function MQTTSubscribeDispatcher : received TemperatureSetpoint =  20
19:32:41.246 function MQTTSubscribeDispatcher : internal_thermostat enabled : saving the setpoint to persistance file
19:32:41.249 function MQTTSubscribeDispatcher : publishing immediately TemperatureSetpoint
19:32:41.263 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualsetpoint/get = 20 °C
19:32:41.268 function forgepayload : Register 13 ,temperature setpoint -16 :  1
19:32:41.294 function MQTTSubscribeDispatcher : sending frame to AC unit:  bytes('7A7A21D5180000A1000000000C01019800000000000017AB')
19:32:41.326 function MQTTSubscribeDispatcher : message received from mqtt
19:32:41.328 function MQTTSubscribeDispatcher : actual ACmode =  heat
19:32:41.330 function MQTTSubscribeDispatcher : actual FanSpeedSetpoint =  auto
19:32:41.342 function MQTTSubscribeDispatcher : actual OscillationModeSetpoint =  on
19:32:41.354 function MQTTSubscribeDispatcher : actual TemperatureSetpoint =  20
19:32:41.356 function MQTTSubscribeDispatcher : received TemperatureSetpoint =  20
19:32:41.368 function MQTTSubscribeDispatcher : internal_thermostat enabled : saving the setpoint to persistance file
19:32:41.371 function MQTTSubscribeDispatcher : publishing immediately TemperatureSetpoint
19:32:41.385 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualsetpoint/get = 20
19:32:41.390 function forgepayload : Register 13 ,temperature setpoint -16 :  1
19:32:41.413 function MQTTSubscribeDispatcher : sending frame to AC unit:  bytes('7A7A21D5180000A1000000000C01019800000000000017AB')
19:32:41.462 function GetFrametype : valid message from AC unit : bytes('7A7AD521220000A30A0A1600000C01019800000000046401DC444231313337306C96')
19:32:41.475 function GetACmode :  ACmodeString =  heat
19:32:41.478 function GetFanSpeed : FanModeString =  auto
19:32:41.480 function GetOscillationMode : OscillationModeString =  on
19:32:41.493 function GetInternalTemperature : internal unit temperature:  22
19:32:41.495 function GetTemperatureSetpoint : TemperatureSetpoint :  20
19:32:41.497 function PublishFeedback : got all needed value, publishing in mqtt topics
19:32:41.511 MQT: CHAUFFAGE/SALON_ANNEXE/tele/mode/get = heat
19:32:41.515 MQT: CHAUFFAGE/SALON_ANNEXE/tele/fan/get = auto
19:32:41.518 MQT: CHAUFFAGE/SALON_ANNEXE/tele/swing/get = on
19:32:41.531 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualtemp/get = 22
19:32:41.534 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualsetpoint/get = 20
19:32:41.762 function GetFrametype : valid message from AC unit : bytes('7A7AD521220000A30A0A1600000C01019800000000046401DC444231313337306C96')
19:32:41.775 function GetACmode :  ACmodeString =  heat
19:32:41.778 function GetFanSpeed : FanModeString =  auto
19:32:41.781 function GetOscillationMode : OscillationModeString =  on
19:32:41.783 function GetInternalTemperature : internal unit temperature:  22
19:32:41.795 function GetTemperatureSetpoint : TemperatureSetpoint :  20
19:32:41.797 function PublishFeedback : got all needed value, publishing in mqtt topics
19:32:41.811 MQT: CHAUFFAGE/SALON_ANNEXE/tele/mode/get = heat
19:32:41.814 MQT: CHAUFFAGE/SALON_ANNEXE/tele/fan/get = auto
19:32:41.817 MQT: CHAUFFAGE/SALON_ANNEXE/tele/swing/get = on
19:32:41.833 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualtemp/get = 22
19:32:41.836 MQT: CHAUFFAGE/SALON_ANNEXE/tele/Actualsetpoint/get = 20

**Comment by ouinouin** [comment]
the function to save flash writes seems not too work, i m looking at it

**Comment by ouinouin** [comment]
@EricBerdah : fixed in commit https://github.com/ouinouin/Berryton/commit/b704949d1cd868d2c316a7d3f3321b343466a12b, you can download again, give a try and give valuable feedback :-)

**Comment by EricBerdah** [comment]
hi, i have made  new tests this morning,
with
thermostat mode  = 0
thermostatoffset = 0

i can change the value of the set point on the AC Unit ( by ex 24°C on the ACunit screen with a beep of confirmation) but 1 second later the AC unit receive an old value (20°C in my case with a beep)
[Berryton Log.txt](https://github.com/user-attachments/files/15944023/Berryton.Log.txt)

**Comment by ouinouin** [comment]
ok, i ll habe a look at the thermostat mode=0, this is not the one i use in my install so i didnt bother much.
thanks for feedback that will be i hope valuable for other users.
i m away from my ac unit, so i ll check remotely, but your reporting is highly appreciated.
just confirm that during your tests you re changing values through mqtt and not through the infrared remote which for now i didnt bother to sync (due to issues with how homeassistant is sending data , this is a bit more challenging).

Le 23 juin 2024 11:36:04 GMT+02:00, EricBerdah ***@***.***> a écrit :

**Comment by EricBerdah** [comment]
I confirm
I’m not using the remote IR to send command to the AC unit

**Comment by EricBerdah** [comment]
Hi,
good news, 
i have made tests with  the latest release you're posted
all are ok : temp , mode, fan and swing 
the temp now is well memorized 
la cerise sur le gateau ;-)
the IR remote control work's fine, command and return to the berryton script are ok (just few seconds to receive the update from the AC, it depend when the last message from the AC unit as been sent)

very good job
thank's a lot

**Comment by ouinouin** [comment]
@EricBerdah : thanks for testing, i intend to push some updates especially to show values on the tasmota webpage, dont hesitate to have a look from times to times.
