### ISSUE TITLE
Howto setup

### ISSUE THREAD

**Issue by RichardDrent** [ouinouin/Berryton#4]
Hi,

I got a bit of trouble to get my head around this all.

I have a HA setup working fine 
I have a mqtt broker running all fine
Have installed Tasmota on a ESP 8266 by https://tasmota.github.io/install/

how/ where do I deploy the Berryton.be script?

can anyone give me a suggestion or a push in the right direction where I can find this info.

thanks a million

**Comment by ouinouin** [comment]
hi, unfortunately berry scripting language is only available on esp32 and not on esp8266, so to start, you have to get an esp32 board.
dont hesitate to ask while you ll have the esp32 board.

l esp8266 ne supporte pas le language de script berry, seul l esp32 supporte le script. il faut d abors se fournir une carte a base d esp32.
b

Le 3 août 2024 15:59:38 GMT+02:00, Richard Drent ***@***.***> a écrit :
